### PR TITLE
V17 Docs Update

### PR DESCRIPTION
**Pull request by gcoonrod**
This PR will hold the ongoing work for backporting the JSDoc comments added in V18.

This will address #1110

### CODE REVIEW

**Comment by evantahler** [comment]
@gcoonrod want me to wait until you are further along to merge?

**Comment by gcoonrod** [comment]
@evantahler Yes. I will remove the Waiting On Poster label and assign this PR to you when I believe it is ready.

**Comment by evantahler** [comment]
Looks great!  There's a merge conflict, but sort that out, and I'll merge it in!
After that, I'll sort out how to have multiple versions of the docs published to the website at the same time

**Comment by evantahler** [comment]
This PR is missing the tooling require to actually build the docs.  `jscoc` in package.json, the theme, the build script, etc.  I'm happy to add those

**Comment by evantahler** [comment]
oh.  I'll merge this and do some cleanup.  `./docs` should be git-ignored.  That's what is failing in the test too.

**Pull request merged**
