### PR TITLE
Adding 2020 Developer survey link

### PR DESCRIPTION
**Pull request by gcoonrod**

### CODE REVIEW

**Comment by gcoonrod** [comment]
Hmm, all those commits seem odd...

**Comment by evantahler** [comment]
Yeah... but I'll squash them so they will go away.  Looks like we've had some merge commits since you last pulled.

**Comment by jamespedid** [comment]
Not sure where else to put this, but the survey forced me to pick that I was using websockets or tcp sockets, even though I do not use either one.

**Comment by evantahler** [comment]
Oops... Thanks!
Screen Shot 2020-02-18 at 1 56 12 PM

**Pull request merged**
