### PR TITLE
add logger support maxLogStringLength config to Response

### PR DESCRIPTION
**Pull request by ShunPin**

### CODE REVIEW

**Comment by ShunPin** [comment]
done

**Comment by evantahler** [comment]
@gcoonrod can you please help with the review?

**Review by gcoonrod — APPROVED** [review]
This looks good to me.

**Comment by evantahler** [comment]
I don't think so - @ShunPin just came with a fix!

**Comment by evantahler** [comment]
Released! https://github.com/actionhero/actionhero/releases/tag/v28.2.2

**Pull request merged**
