### PR TITLE
Browser tests with Puppeteer rather than Selenium

### PR DESCRIPTION
**Pull request by evantahler**
In theory, Puppeteer is will be easier for folks to use.  It works cross-platform, knows how to install it's own version of Chrome and doesn't have an external dependency like `chrome-webdriver`.   

If only I can get it to run on CI...

### CODE REVIEW

**Comment by gcoonrod** [comment]
What is the reasoning behind this change?

**Comment by evantahler** [comment]
Updated the description!

**Comment by evantahler** [comment]
Ideas from Clay (from slack) https://gist.github.com/chimmelb/6342504893b2b9fce0f4a8efd096ae60

**Comment by evantahler** [comment]
Thanks to @allyusd and #1654 the tests are passing!

**Review by gcoonrod — APPROVED** [review]

**Pull request merged**
