### PR TITLE
Fix loading a locked item

### PR DESCRIPTION
**Pull request by cecofreeman**
An item is loaded from the cache and is eventually old copy, because first is loaded and then is checked for locking. In such a case the locker worker may apply changes to the item during the lock, but we don't receive a fresh copy for the item. This fix is checking for lock first and then tries to load the item.

### CODE REVIEW

**Comment by evantahler** [comment]
This looks like a good fix! Can you please provide a test that proves the behavior (and so it won't break in this way again?)

Thanks!

**Comment by cecofreeman** [comment]
Hello,
Thank you for the comment!
Will try to provide the test within couple of days.

Regards

**Comment by evantahler** [comment]
Checking in again! I've updated your branch with the latest changes from master

**Comment by evantahler** [comment]
closing in favor of https://github.com/actionhero/actionhero/pull/1410

**Pull request closed without merging**
