### PR TITLE
Fix glob problems with path's in windows, safeGlobSync implemented.

### PR DESCRIPTION
**Pull request by YamCrack**
Closes https://github.com/actionhero/actionhero/issues/2275

### CODE REVIEW

**Comment by evantahler** [comment]
Please update the title to describe what this work does and provide a description of this work

**Review by evantahler — COMMENTED** [review]
This looks good! 
Please add a test asserting that all the files you expect in a directory are returned.

**Comment by YamCrack** [comment]
image
he escrito esta prueba, crees que es suficiente?

**Comment by evantahler** [comment]
> I have written this test, do you think it is enough?

Yes! Es perfecto.

**Review by evantahler — APPROVED** [review]
🥳

**Comment by evantahler** [comment]
Released in https://github.com/actionhero/actionhero/releases/tag/v28.1.12

**Pull request merged**
