### PR TITLE
Fix: Actionhero fails to parse locally scoped IPv6 addresses

### LINKED ISSUE #1178: Actionhero fails to parse locally scoped IPv6 addresses
# Name of Issue: Actionhero fails to parse locally scoped IPv6 addresses
Description of Issue: Actionhero will throw 'failed to parse address' when calling api.utils.parseIPv6URI with an IPv6 address containing an address scope (e.g. ::%eth0). For an overview about scoped addresses see [Wikipedia - IPv6 Address - Scoped literal](https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses). The currently used regex to parse incomming IPv6 addresses will fail to match scoped addresses.

- ActionHero Version: `18.1.1`
- Node.js Version: all
- Operating System: all

# Steps to reproduce your error
- Send a request to Actionhero containing a 'x-forwarded-for' header with a scoped IPv6 address
- [alternatively call any other function that relies on api.utils.parseIPv6URI or call it directly with such an address]
- Such an address could be [fe80::1ff:fe23:4567:890a%eth2]:12345

# Workaround / Fix
- Include the scope in the resulting host part of the parsed address by changing the regex
- My current change to get Actionhero working looks like this: `let regexp = new RegExp(/\[([0-9a-f:]+(?:%.+)?)]:([0-9]{1,5})/)`, it will not mess with the match order

# Misc
I saw previous issues with the IPv6 parsing in the project issue history. @evantahler: You stated you might want to include a external lib to handle this. I'm not sure if - and how many of such edge cases potentially exist that are still not covered by the current regex or my extension of it.

### PR DESCRIPTION
**Pull request by aurasalexander**
* fix ipv6 parsing for locally scoped URIs
+ added tests for locally scoped URIs

Resolves #1178

### CODE REVIEW

**Comment by evantahler** [comment]
There's something shady going on with your fork of ActionHero... I think you haven't updated it since August.  You are still testing older versions of node which we have moved on from.  Can you please rebase your changes from master and try again?

Thanks!

**Comment by evantahler** [comment]
... other than that, the change looks great!

**Comment by aurasalexander** [comment]
Oh! I'm sorry. I had some issues updating my branch to the current HEAD. I thought I tackled them as the files changed in this request were seemingly correct. I'll look into it again soon.

**Comment by aurasalexander** [comment]
I rebased my branch. Could you please check if the fork issue is resolved now?

**Comment by evantahler** [comment]
Awesome! Thanks!

**Pull request merged**
