### PR TITLE
Add a Code of Conduct for the Actionhero Community

### PR DESCRIPTION
**Pull request by evantahler**
If you are in the USA, this week has been a difficult one.  This has been a week of turmoil and protests catalyzed by (yet another) unjust killing of a citizen at the hands of of the people who should be protecting all of us.  I try hard to not entangle this community with larger societal issues - to keep us focused only on code and APIs... but sometimes the real world intervenes. 

When thinking about what small things I can do to help ensure that the communities I'm a part of are open to _all_ people, I realized that I've been negligent in drafting a Code of Conduct for our community.   This PR adds a Code of Conduct that will govern those of us who work on Actionhero going forward, and to codify my goal of making our community as available as possible to the most people. 

I feel that it is also important to say that I've personally always had pleasant interactions with everyone in the Actionhero community.   On the whole, I think we are a polite, smart, and diverse group of people.  This document's aim is to keep our community that way!   However, my experiences might not be the same as yours.   As this Code of Conduct states - if you experience a problem with someone in the Actionhero community, please email help@actionherojs.com so we can address the the problem.  There are tools available to us via the platforms we have chosen to use (Github, Slack, etc) to help with moderation, privacy, etc. 

I've chosen to base our Code of Conduct on the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/), which has been adopted by almost 400,000 other open source projects.

### CODE REVIEW

**Comment by evantahler** [comment]
Github will display this file automatically a link on all new PRs and Issues. Thanks @github! 

83366663-67663f80-a365-11ea-9872-c40ca8fa125b

**Comment by evantahler** [comment]
I've opted to add the Actionhero project as an adopter of the Contributor Covenant Code of Conduct via https://github.com/ContributorCovenant/contributor_covenant/pull/785

**Comment by CoralineAda** [comment]
@evantahler If you would consider a GOVERNANCE.md next (tooling at https://communityrule.info) your project could qualify as Ethical Open Source (https://ethicalsource.dev/definition/)

**Comment by evantahler** [comment]
Fascinating! I'll take a look! 
Moved to https://github.com/actionhero/actionhero/issues/1484 so this idea doesn't get lost.

**Pull request merged**
