### PR TITLE
Add action response to logger and user can disable and filter private…

### PR DESCRIPTION
**Pull request by ShunPin**
I add action response object to logger.
User can disable this by set enableResponseLogging = false in config/api.ts.
And when the response object contain private information, it can be filter by set filteredResponse to whatever you want.

### CODE REVIEW

**Comment by evantahler** [comment]
This is great work @ShunPin! Thank you for doing this!   Good testing too!

My only comment is that I think that by default, logging the response should be disabled.  When comparing similar features with other frameworks, and nginx & rails - they all do not log the response payload.  I believe that we should follow the same default pattern to, by default, protect user data, which is very likely to be logged in the response payload.

**Comment by evantahler** [comment]
Also, I just updated https://github.com/actionhero/actionhero/commit/0c250babec50289bda6528ee18c841c4cea9b108 so the test suite should no run on all Pull Requests

**Comment by ShunPin** [comment]
I forgot to remove testing log.
so a new PR just now.

**Comment by evantahler** [comment]
Awesome work! Thank you!

**Pull request merged**
