### PR TITLE
Custom loaders

### PR DESCRIPTION
**Pull request by billybonks**
Following this conversation https://github.com/actionhero/actionhero/issues/1074. @crrobinson14 @evantahler 

I made an example of what i am thinking, i think this is a good solution because it doesn't break anything for existing projects, but adds a point of customisation for those who want. it also allows me to share my customisations via ah-plugins.

`loaders/task.js` allows me to use a different syntax for my tasks, and easily change it as i require more features.

```
module.exports = function(fullFilePath) {
  const klass = require(fullFilePath);

  function makeRunner(context){
    function runner (api, params, next){
      let _task = new context.klass;
      _task.run(params).then(() =>{ next(); }).catch(next);
    }
    return runner;
  }

  let task = {
    name: klass.name,
    klass: klass,
    description:   '  ',
    queue:         'default',
    frequency:     0,
  };

  task.run = makeRunner(task);
  return [task];
};
```
`loaders/console.js` allows me to modify my repl env
```
module.exports = function(repl) {
  repl.context.test = 'asd';
};
```
i am using the default loader for actions.

### CODE REVIEW

**Comment by evantahler** [comment]
Please check the test suite.  Some of your style doesn't pass the linter.  Also, please lock in the behavior you expect with a test.

**Comment by billybonks** [comment]
will do so the overall strategy looks okay to you ?

**Comment by evantahler** [comment]
I'm personally having trouble imaging a use case... but I'm sure that's because I've been stuck inside of ActionHero for too long... can you share a full example (with multiple files) in your PR's description?  The example you have now looks to me like it can be accomplished within the structure that exists already.

**Comment by usebaz** [comment]
I think this is not necessary functionality. It is too specific and rarely used. And unclear

**Comment by evantahler** [comment]
@billybonks Also, we would require a test added which locks-in your new functionality, which could also help explain the use-case you have.

**Comment by billybonks** [comment]
Sorry for the delay on finalising this, it will be ready by Monday for
sure. Thanks for your patience :)

**Comment by billybonks** [comment]
sorry again for the delay very, tied up atm. @evantahler  when I try to run the test I just get

image

**Comment by evantahler** [comment]
I don't think I see what the problem is? Join us on slack if you need help!

**Comment by evantahler** [comment]
I'm closing this as the next version of actionHero will require that actions and tasks are ES6 classes, which can be easily extended however you like.  Also, all run methods will be async methods, so there will be no ned for a promise-ify wrapper like your example!  

For example: https://github.com/actionhero/actionhero/pull/1098

**Comment by billybonks** [comment]
awesome thanks :)

**Pull request closed without merging**
